extends Object

enum MATCH_SUITS { CLUBS, SPADES , HEARTS, DIAMONDS, DONKEY, HORSE, COW, ZEBRA, BIRD, DOG, CAT, SUPERMAN, BATMAN, SPIDERMAN, BAGELS, BREAD, RICE, PIZZA, WATER, SODA, PISS, GRASS, FIRE, STEEL, GROUND, PSYCHIC, FAIRY }
